### ISSUE TITLE
feature request: readline-style transponse

### ISSUE THREAD

**Issue by leahneukirchen** [jart/bestline#12]
In readline and editline (and zle and emacs), CTRL-T transposes two letters as in bestline, but with the following addition: if cursor is at eol, swap the two last letters:

```
> ab<CTRL-T>
> ba
```

readline also implements this for ALT-T to transpose the last two words:
```
$ foo bar<ALT-T>
$ bar foo
```

**Comment by jart** [comment]
CTRL-T is an easy fix. I can do ALT-T at end of line too, however it's going to slightly differ from readline for the time being in terms of corner cases with spacing. Let me know if it works out for you!

**Comment by leahneukirchen** [comment]
Looks good, thanks!
