### ISSUE TITLE
bestline on Windows ?

### ISSUE THREAD

**Issue by vtorri** [jart/bestline#26]
Hello

Windows has now an emulation of pty (called ConPTY) and it seems that there are some support of VT100 codes. For example : https://learn.microsoft.com/en-us/windows/terminal/samples

do you think it would be possible to port bestline to conpty ?

**Comment by jart** [comment]
Thanks for asking. You need to use a POSIX platform if you want to use bestline. This project won't support WIN32. You can use Cygwin or WSL2.

**Comment by badiku** [comment]
what does this means: `Support running on Windows in MinTTY or CMD.EXE on Win10+` ?
