### ISSUE TITLE
It's unclear what does `ez` mean in `ezbestline` function name.

### ISSUE THREAD

**Issue by alexey-milovidov** [jart/bestline#3]
Some cultural reference that I don't get?

PS. Maybe `ez` means `easy`, then the function better to be named `easy_bestline`.
Or better, `bestline_with_history` - so our grandchildren will be able to grok the code.

**Comment by jart** [comment]
Per your feedback I've renamed `ezbestline` to `bestlineWithHistory`. Thanks! dfec5f264958e21a3586ae85c1c1a8d8574cef75
