### ISSUE TITLE
日本 (Japan) should be replaced with 日本語 (Japanese language) in the list of supported languages

### ISSUE THREAD

**Issue by mbrukman** [jart/bestline#6]
One of the lines in the README:

https://github.com/jart/bestline/blob/67f41f0badb9df75e20cafe5d2cc97bef31240de/README.md#L111

uses 日本 in a list of supported languages to mean "Japanese". However, 日本 (Nihon) is Japan (the country), whereas what you probably intended to use here is 日本語 (Nihongo) which is the Japanese language.

Sources:

* 日本: [Jisho](https://jisho.org/search/%E6%97%A5%E6%9C%AC), [Wiktionary](https://en.wiktionary.org/wiki/%E6%97%A5%E6%9C%AC#Japanese)
* 日本語: [Jisho](https://jisho.org/search/%E6%97%A5%E6%9C%AC%E8%AA%9E), [Wiktionary](https://en.wiktionary.org/wiki/%E6%97%A5%E6%9C%AC%E8%AA%9E#Japanese)

**Comment by jart** [comment]
Thanks! fixed.
